# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'InstructionsCocoaPods' do
  pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'main'
end
